/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VanDao2k
 */
public class Congvanden extends javax.swing.JFrame {
    public static menuCV ViewMenuCV = new menuCV();

    DefaultTableModel tbn =  new DefaultTableModel();
    public Congvanden() {
        initComponents();
      loadcommoBoxBoPhan();
      loadcommoBoxLoaicongvan();
      loadData();
    }
public void loadcommoBoxBoPhan(){
    try {
        connection a = new connection();
        Connection conn = a.getConnection();
        PreparedStatement ps = conn.prepareStatement("Select tenbophan from bophan  ");
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
            cbbophan.addItem(rs.getString("tenbophan"));
            
            
        }
    } catch (Exception e) {
        System.out.println(e.toString());
    }
}public void loadcommoBoxLoaicongvan(){
    try {
        connection a = new connection();
        Connection conn = a.getConnection();
        PreparedStatement ps = conn.prepareStatement("Select loaicongvan from loaicongvan group by loaicongvan");
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
            cbloaicongvan.addItem(rs.getString("loaicongvan"));
            
        }
    } catch (Exception e) {
        System.out.println(e.toString());
    }
}


public void loadData(){
    try {
        connection a = new connection();
        Connection conn = a.getConnection();
        int number;
        Vector row,column;
        tbn.setRowCount(0);
        column = new Vector();
        Statement st = conn.createStatement();
   
        ResultSet rs =st.executeQuery("select * from congvanden");
        ResultSetMetaData metaData =rs.getMetaData();
        number = metaData.getColumnCount();
       for(int i = 1;i <=number;i++){
           column.add(metaData.getColumnName(i));
          
       }
       tbn.setColumnIdentifiers(column);
       
       while(rs.next()){
           row = new Vector();
           for(int i = 1 ; i <=number;i++){
              row.addElement(rs.getString(i));
           }
           tbn.addRow(row);
           jTable1.setModel(tbn);
       }
       
   jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
          if(jTable1.getSelectedRow()>=0){
              txtsocvd.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0)+"");
                 txttencvd.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1)+"");
                 txttrichyeu.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2)+"");                
              try {
                    DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
                  Date date =   new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(jTable1.getSelectedRow(),3)+"");
                 DateNhan.setDate(date);
              } catch (ParseException ex) {
                  Logger.getLogger(Congvanden.class.getName()).log(Level.SEVERE, null, ex);
              }
                     
              try {
                    DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
                  Date date =   new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(jTable1.getSelectedRow(),4)+"");
                 DateKy.setDate(date);
              } catch (ParseException ex) {
                  Logger.getLogger(Congvanden.class.getName()).log(Level.SEVERE, null, ex);
              }
     
              
                 txttenlanhdao.setText(jTable1.getValueAt(jTable1.getSelectedRow(),5)+"");
                 cbloaicongvan.setSelectedItem(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),6)+"");
                 cbbophan.setSelectedItem(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),7)+"");
          }
            }
        });
    } catch (Exception ex) {
        System.out.println(ex.toString());
    }
}







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttencvd = new javax.swing.JTextField();
        txttrichyeu = new javax.swing.JTextField();
        txtsocvd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttenlanhdao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbloaicongvan = new javax.swing.JComboBox<>();
        cbbophan = new javax.swing.JComboBox<>();
        btnsua = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DateNhan = new com.toedter.calendar.JDateChooser();
        DateKy = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Công Văn Đến");

        jLabel2.setText("Tên Công Văn Đến");

        jLabel3.setText("Trích Yếu");

        jLabel4.setText("Ngày Nhận");

        jLabel5.setText("Số Công Văn Đến");

        txttrichyeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrichyeuActionPerformed(evt);
            }
        });

        txtsocvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsocvdActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã Loại Công Văn");

        jLabel7.setText("MÃ Bộ Phận");

        jLabel8.setText("Ngày Ký");

        jLabel9.setText("Người Ký");

        cbloaicongvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbloaicongvanActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("<");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnthem)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsocvd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttencvd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttrichyeu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DateNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbloaicongvan, 0, 105, Short.MAX_VALUE)
                                    .addComponent(cbbophan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttenlanhdao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsua)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoa)))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsocvd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbloaicongvan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbophan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txttencvd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttenlanhdao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttrichyeu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsua)
                    .addComponent(btnthem)
                    .addComponent(btnxoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(718, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttrichyeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrichyeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrichyeuActionPerformed

    private void txtsocvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsocvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsocvdActionPerformed

    private void cbloaicongvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbloaicongvanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbloaicongvanActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
       try {
            connection a = new connection();
        Connection conn = a.getConnection();

      PreparedStatement ps = conn.prepareStatement("insert into congvanden value(?,?,?,?,?,?,?,?)");
      ps.setString(1,txtsocvd.getText().toString());
        ps.setString(2,txttencvd.getText().toString());
         ps.setString(3,txttrichyeu.getText().toString());
       SimpleDateFormat sdf =   new SimpleDateFormat("yyyy-MM-dd");
       String datenhan = sdf.format(DateNhan.getDate());
        String dateky = sdf.format(DateKy.getDate());
         ps.setString(4,datenhan);
          ps.setString(5,dateky);
           ps.setString(6,txttenlanhdao.getText().toString());
       ps.setString(7,cbloaicongvan.getSelectedItem().toString());
        ps.setString(8,cbbophan.getSelectedItem().toString());
           ps.executeUpdate();
          
                JOptionPane.showMessageDialog(this,"Thêm Thành Công");
           tbn.setColumnCount(0);
                loadData();
      
        } catch (Exception e) {
            System.out.println(e.toString());
        }                 
        
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
       try{
        connection a = new connection();
        Connection conn = a.getConnection();
      PreparedStatement ps = conn.prepareStatement("Update congvanden set tencongvanden = ?,trichyeu = ?,ngaynhan = ?,ngayky = ?,nguoiky=?,maloaicongvan=?,maloaibophan=? where socongvanden = ?");
      ps.setString(8,txtsocvd.getText());
        ps.setString(1,txttencvd.getText());
          ps.setString(2,txttrichyeu.getText());
          SimpleDateFormat sdf =   new SimpleDateFormat("yyyy-MM-dd");
       String datenhan = sdf.format(DateNhan.getDate());
        String dateky = sdf.format(DateKy.getDate());
         ps.setString(3,datenhan);
          ps.setString(4,dateky);
              ps.setString(5,txttenlanhdao.getText());
               ps.setString(6,cbloaicongvan.getSelectedItem().toString());
                ps.setString(7,cbbophan.getSelectedItem().toString());
            ps.executeUpdate();
       
                JOptionPane.showMessageDialog(this,"Sửa Thành Công ");
           tbn.setColumnCount(0);
                loadData();
           
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
          try {
               connection a = new connection();
        Connection conn = a.getConnection();
      PreparedStatement ps = conn.prepareStatement("delete from congvanden where socongvanden = ?");
      ps.setString(1,jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
      if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa  công văn này ? "," Xác Nhận",
             JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
          ps.executeUpdate();
          tbn.setRowCount(0);
            loadData();
      }
    
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        ViewMenuCV.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Congvanden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Congvanden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Congvanden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congvanden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Congvanden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateKy;
    private com.toedter.calendar.JDateChooser DateNhan;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbbophan;
    private javax.swing.JComboBox<String> cbloaicongvan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtsocvd;
    private javax.swing.JTextField txttencvd;
    private javax.swing.JTextField txttenlanhdao;
    private javax.swing.JTextField txttrichyeu;
    // End of variables declaration//GEN-END:variables
}
